#pragma once
#ifndef COUNTRIESPOPULATION__PROGRAMCOUNTRIESPOPULATION_H_
#define COUNTRIESPOPULATION__PROGRAMCOUNTRIESPOPULATION_H_

class ProgramCountriesPopulation {
public:
	static int main();
	
};

#endif //COUNTRIESPOPULATION__PROGRAMCOUNTRIESPOPULATION_H_
